/*
DAEE Playtest Aid Utility Procedures
*/

package playtest_aid

import "core:fmt"
import "core:strings"
import "core:strconv"
import "core:math/rand"
import "base:intrinsics"
import "base:runtime"


// --------------------------   PUBLIC STRUCTS   ------------------------------

// Represents the information needed for an entity in an encounter
// - IntPairs represent <currentValue, valueToResetTo> for ease  
//@(export)
Entity :: struct {
    name: string,
    initiative: int,
    health: Pair(int),
    armour: Pair(int),
    repair: Pair(int),
    will: Pair(int),
    wisdom: Pair(int),
    perspective: Pair(int),
    status: [Statuses]int,
}

//@(export)
Statuses :: enum {
   BURN,
   FREEZE,
   ACID,
   POISON,
   DEADLY_POISON,
   BLEED,
}

/*
Narai Risser, William Duprey
3/31/26
A struct that uses parametric polymorphism to work for any type.
Will this be used for anything other than integers? I don't know.
But it can be!
- $T specifies a compile-time typeid used by the fields
- The where statement ensures that T is a numeric type,
  which is good, because we will be doing numeric things
  with the fields in this struct. 
- The type_is_numeric procedure must be able to be evaluated 
  at compile-time, and since $T is a compile-time parameter, 
  (and types are compile-time constants) we're groovy.
*/
//@(export)
Pair :: struct($T: typeid) where intrinsics.type_is_numeric(T) {
    current : T,
    max     : T
}

// -------------------------- PUBLIC  PROCEDURES ------------------------------

/*
William Duprey
3/25/26
Initializes the random number generator using the provided seed.
- Do we want this functionality? Should an encounter be 
  deterministically random? 
  - YES
*/
//@(export)
init_rand :: proc "c" (seed: u64){
    // Context is not provided by default when called in C,
    // so anything that needs the context needs to set it like this
    // at the start of the procedure
    context = runtime.default_context()
    rand.reset(seed)
}

/*
William Duprey
3/25/26
Simulates the rolling of dice. Explicit procedure overloading!
The two overloaded procedures have @(private="file"), meaning they cannot
be accessed outside of this file. Hooray for encapsulation?
Hopefully as a utility procedure, this is more helpful than annoying.
*/
roll_dice :: proc{roll_dice_mod, roll_dice_no_mod, roll_dice_string }

/*
William Duprey
4/8/26
Damages the entity. 
Returns the damage dealt to armour and health as separate integers.
*/
damage_entity :: proc{damage_entity_dice, damage_entity_flat}

/*
William Duprey
4/9/26
Heals the entity. 
Returns the total amount healed.
- Note: be careful with procedure overloading. Having multiple
default values (of differing types?) seems to mess things up.
*/
heal_entity :: proc{heal_entity_dice, heal_entity_flat}

// Resets primary resources used for abilities 
//@(export)
ResetEntityKarma :: proc "c" (entity : ^Entity) {
    ResetPair(&entity.will       )
    ResetPair(&entity.wisdom     )
    ResetPair(&entity.perspective)
}

/*
Narai Risser, William Duprey
3/31/26
Resets the pair by setting its current field equal to its maximum.
- When the compiler sees that code calls this procedure, it will
  generate a version of ResetPair where it replaces T with the 
  type of argument fed into the parameter. It generates as many
  versions of ResetPair as different types are called for it.
- If ResetPair is called multiple times with the same type,
  there is still just one version of the procedure generated by
  the compiler.
- Don't need to include a where statement to force numeric types,
  since the Pair struct already does that.
*/
//@(export)
ResetPair :: proc "c" (pair: ^Pair($T)) {
    pair.current = pair.max
}

/*
William Duprey
4/22/26
Spends karma points, assuming the entity has enough to spend.
- entity: pointer to the entity spending karma points
- will: will points to spend
- wis: wisdom points to spend
- per: perspective points to spend
*/
//@(export)
spend_karma :: proc "c" (entity: ^Entity, will, wis, per: int) {
    context = runtime.default_context()
    
    // Make sure we don't blow up
    assert(entity != nil, "Invalid argument to spend_karma: entity cannot be nil")
    assert(entity.will.current >= will, fmt.tprintf(
        "Invalid argument to spend_karma: entity has %v will," + 
        "but tried to spend %v will", entity.will.current, will)
    )
    assert(entity.wisdom.current >= wis, fmt.tprintf(
        "Invalid argument to spend_karma: entity has %v wis," + 
        "but tried to spend %v wis", entity.wisdom.current, wis)
    )
    assert(entity.perspective.current >= per, fmt.tprintf(
        "Invalid argument to spend_karma: entity has %v will," + 
        "but tried to spend %v will", entity.perspective.current, per)
    )

    // Only bother doing anything if there are actual values
    // - Given Odin's friendliness, the parantheses around
    //   entity.<karma> probably aren't required, but better
    //   safe than sorry
    // - reduce_pair won't reduce if it would take the pair's current
    //   value below 0, so technically the above asserts don't
    //   need to be there. But having an error message like that
    //   is useful, so they stay
    if(will > 0) { reduce_pair(&(entity.will), will) }
    if(wis > 0) { reduce_pair(&(entity.wisdom), wis) }
    if(per > 0) { reduce_pair(&(entity.perspective), per) }
}

/*
William Duprey
4/9/26
Generic procedure to increase a pair's current field by an amount n.
If overflow is false, current will be capped at the pair's maximum.
This procedure could be used for any of an Entity's pair fields, not
just health.
- pair: the pair to be modified (pointer to a Pair of some numeric type)
- n: value to increase the pair's current field (some numeric type)
- overflow: whether to cap the current field (boolean)
*/
//@(export)
heal_pair :: proc "c" (pair: ^Pair($T), n: T, overflow: bool){
    if(overflow){
        pair.current += n   // max be damned
    } else{
        pair.current = min(pair.current + n, pair.max) // max be adhered to
    }
}

/*
William Duprey
4/12/26
Generic procedure to reduce a pair's current field by an amount n.
If n would reduce current below 0, nothing happens.
- pair: the pair to be modified (pointer to a Pair of some numeric type)
- n: value to reduce the pair's current field (some numeric type)
*/
//@(export)
reduce_pair :: proc "c" (pair: ^Pair($T), n: T){
    value: T = pair.current - n;    // Do this math only once
    
    // Only apply the reduction if the result is 0 or higher
    if(value >= 0){
        pair.current = value;
    }
}

/*
William Duprey
4/16/26
Adds a number of stacks of the given status to the entity.
- entity: pointer to the entity
- status: the type of status to add
- count: number of status stacks to add
*/
//@(export)
add_status :: proc "c" (entity: ^Entity, status: Statuses, count: int){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to add_status: entity pointer cannot be nil")
    assert(count > 0, "Invalid argument to add_status: status count must be at least 1")

    entity.status[status] += count
}

/*
William Duprey
4/16/26
Adds 1 to the stacks of the given status on the entity.
- entity: pointer to the entity
- status: the type of status to add
*/
//@(export)
increment_status :: proc "c" (entity: ^Entity, status: Statuses){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to increment_status: entity pointer cannot be nil")
    
    entity.status[status] += 1
}

/*
William Duprey
4/16/26
Remove status overload. 
- 2 parameters = remove all status counts.
- 3 parameters = remove a number of status counts.
*/
remove_status :: proc{ remove_status_all, remove_status_count }

/*
William Duprey
4/16/26
Removes 1 from the stacks of the given status on the entity.
- entity: pointer to the entity
- status: the type of status to decrement
*/
//@(export)
decrement_status :: proc "c" (entity: ^Entity, status: Statuses){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to decrement_status: entity pointer cannot be nil")
    
    // Reduce status count to a max of 0
    entity.status[status] = max(0, entity.status[status] - 1)
}

/*
William Duprey
4/16/26
Applies the number of status stacks to the entity.
- entity: pointer to the entity to set the status of
- status: the type of status to set
- count: the number of stacks of status to set
*/
//@(export)
set_status :: proc "c" (entity: ^Entity, status: Statuses, count: int){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to set_status: entity pointer cannot be nil")
    assert(count >= 0, "Invalid argument to set_status: status count must be at least 0")

    entity.status[status] = count
}


// -------------------------- PRIVATE PROCEDURES ------------------------------
/*
William Duprey
3/26/26
Simulates the rolling of dice. Each die can roll
between 1 and its size. Each die roll is summed
together, a modifier is added, and the result (int) is returned.
- count: number of dice to roll (int)
- size: number of sides on each die (int)
- mod: number added to the roll (int)
I considered making count and size unsigned integers to prevent 
the values from being negative, but that just created a headache
with type conversions. Assert statements do practically the same
thing of ensuring valid values, and they also include an error message.
*/
@(export=true, link_name="roll_dice_mod")
roll_dice_mod :: proc "c" (count, size, mod: int) -> (result: int) {
    context = runtime.default_context()
    // Need to put the parameter shadowing at the very start
    // of the procedure so that the compiler is extra happy
    size := size;
    
    // I love having a strongly-typed language. I love not needing
    // to ensure the arguments are actually integers and not floats 
    // or strings or whatever JavaScript nonsense they can be.
    // I am content.
    
    // Rolling negative dice doesn't make sense. Rolling 0 dice
    // could make sense if you just want the modifier?
    assert(count > -1, "Invalid argument to rollDice: count must be greater than -1")
    
    // Can't have a die with 0 sides. 1 side isn't very useful, but
    // is still technically reasonable. 
    assert(size > 0, "Invalid argument to rollDice: size must be greater than 0")

    // Don't even need this, since zero-initialization is a thing,
    // and the variable is created as part of the procedure declaration
    //result = 0

    // Store the true upper bound to avoid the unseemly, costly
    // operation of adding 1 on every loop iteration. My word,
    // can you imagine the scandal?
    // - Normally procedure parameters are immutable, but shadowing
    //   the variable like this allows it to be modified locally.
    // - Could this be avoided by just passing in the size as 
    //   1 higher than the max roll? Sure, but that's an annoying
    //   thing to make whatever calls this procedure have to do.
    // - Could this also be avoided by adding 1 on each iteration?
    //   Sure, but that's nasty. O(1) or O(n), folks.
    //   I figure speed matters more than memory usage in this case.
    // - Is this an absurbly long comment for just this one line?
    //   Absolutely. I make no apologies for what I am.
    size = size + 1

    // For _ in the range of 0 to count (exclusive)
    // - _ means we don't care about the value, it isn't used 
    //   within the loop besides tracking the iteration
    for _ in 0..<count {
        result += rand.int_range(1, size) // roll a die, sum it
    }

    return result + mod // don't forget the modifier
}

/*
William Duprey
3/25/26
Simulates the rolling of dice. Each die can roll
between 1 and its size. Each die roll is summed
together, and the result (int) is returned.
- count: number of dice to roll (int)
- size: number of sides on each die (int)
This procedure calls the procedure that includes
a modifier argument and passes a 0.
*/
//@(export)
roll_dice_no_mod :: proc "c" (count, size: int) -> (int){
    return roll_dice_mod(count, size, 0);
}

/*
William Duprey
4/23/26
Simulates the rolling of dice. Each die can roll
between 1 and its size. Each die roll is summed
together, and the result (int) is returned.
- dice: string formatted like AdB, with optional +/-C
TODO: Move this to main so that util doesn't have to 
      import so much? Hmmm... Not sure.
*/
//@(export=true, link_name="roll_dice_string")
roll_dice_string :: proc "c" (cdice: cstring) -> (int){
    context = runtime.default_context()
    dice: string = string(cdice)
    
    assert(strings.contains(dice, "d"), "Invalid argument to roll_dice_string: string did not contain \"d\"")

    // --- Variable Setup ---
    count, size, mod: int   // 3 ints to be parsed from the string
    arr1: []string  // Substring array, split by "d"

    // Below variables are unused if there is no modifier
    arr2: []string  // Substring array, split by "+" or "-"
    modSign: string // Either "+" or "-", used to split the "B+C" string
    negate: int = 1 // Either 1 or -1

    // --- Split by "d" ---
    // strings.split allocates memory for the string array returned
    // - Using _ to signify we don't care about errors. It might be good
    //   to care, but this is a quick and dirty implementation
    arr1, _ = strings.split(dice, "d") // arr1 = ["A", "B+C"]
    defer delete(arr1)  // preemptively clean up
    count, _ = strconv.parse_int(arr1[0])  // Parse dice count

    // --- Branch based on modifier ---
    if(strings.contains(arr1[1], "+")){         // --- positive mod ---
        modSign = "+"
    } else if(strings.contains(arr1[1], "-")){  // --- negative mod ---
        modSign = "-"
        negate = -1
    } else {                                     // --- no mod ---
        // End early if there's no mod
        // - defer from above ensures arr1 gets deleted properly
        size, _ = strconv.parse_int(arr1[1])
        return roll_dice_mod(count, size, 0)        
    }

    // --- Split by "+" or "-" ---
    arr2, _ = strings.split(arr1[1], modSign)
    defer delete(arr2)

    // Parse substrings into integers using imported strconv
    size, _ = strconv.parse_int(arr2[0])
    mod, _ = strconv.parse_int(arr2[1])

    // Since "-" is used to split the string, the negative
    // is lost, so we have to negate the mod manually
    mod *= negate

    // Finally, roll them dice
    // - arr1 and arr2 are properly deleted because of the defers
    return roll_dice_mod(count, size, mod)
}

/*
William Duprey
4/8/26
Damages the entity by rolling a damage number. Damage is
first applied to armour, then health, unless the ignoreArmour
boolean is set to true.
- entity: Entity struct to modify (Entity pointer)
- dCount: number of damage dice to roll (int)
- dSize: size of damage dice being rolled (int)
- dMod: modifier to damage roll (int)
        Defaults to 0
- ignoreArmour: whether to deal damage directly to health (bool)
                Defaults to false (meaning armour is damaged)
Returns the damage dealt to armour and health as separate integers.
*/
//@(export)
damage_entity_dice :: proc "c" (entity: ^Entity, dCount, dSize, dMod: int, ignoreArmour: bool) -> (healthDmg: int){
    // Roll the dice
    damage: int = roll_dice_mod(dCount, dSize, dMod)

    armourDmg: int

    // Rely on the override to do the actual work
    healthDmg = damage_entity_flat(entity, damage, ignoreArmour)
    return
}

/*
William Duprey
4/8/26
Damages the entity by a set value. Damage is
first applied to armour, then health, unless the ignoreArmour
boolean is set to true.
- entity: Entity struct to modify (Entity pointer)
- damage: amount to inflict (int)
- ignoreArmour: whether to deal damage directly to health (bool)
                Defaults to false (meaning armour is damaged)
Returns the damage dealt to armour and health as separate integers.
*/
//@(export)
damage_entity_flat :: proc "c" (entity: ^Entity, damage: int, ignoreArmour: bool) -> (healthDmg: int){
    // Shadow the damage parameter so it can be changed
    damage := damage
    
    armourDmg: int
    
    context = runtime.default_context()

    // Make sure we don't blow up from a nil pointer
    // or weird math happening with negative damage
    assert(entity != nil, "Invalid argument to damage_entity: entity pointer cannot be nil")
    assert(damage >= 0, "Invalid argument to damage_entity: damage cannot be negative")

    // Retrieve armour and health values from the entity struct
    // to avoid repeatedly accessing its fields
    // - Normally, the -> syntax would be required since entity
    //   is a pointer. But Odin is nice and does that implicitly
    //   when we have a struct pointer and use the dot notation.
    armour: int = entity.armour.current
    health: int = entity.health.current

    if(!ignoreArmour){
        // Apply that damage to armour
        armour -= damage

        // If overflow happens, set armour to 0, 
        // and apply the remainder to health
        if(armour < 0){
            damage = -armour // Invert negative armour for leftover damage
            armour = 0
        }
    }

    // Keep health at or above 0
    health = max(0, health - damage)

    // Compare the starting armour and health to get the damage dealt
    armourDmg = entity.armour.current - armour
    healthDmg = entity.health.current - health

    // Actually apply the new values to the entity
    entity.armour.current = armour
    entity.health.current = health

    return // armourDmg, healthDmg
}

/*
William Duprey
4/9/26
Heals the entity by rolling dice.
- entity: Entity struct to modify (Entity pointer)
- dCount: number of damage dice to roll (int)
- dSize: size of damage dice being rolled (int)
- dMod: modifier to damage roll (int)
        Defaults to 0
- overheal: whether to cap healing at max health
            Defaults to false
Returns the damage dealt to armour and health as separate integers.
*/
//@(export)
heal_entity_dice :: proc "c" (entity: ^Entity, dCount, dSize, dMod: int, overheal: bool) -> (healthRestored: int){
    // Roll the dice
    healing: int = roll_dice_mod(dCount, dSize, dMod)

    // Rely on the override to do the actual work
    healthRestored = heal_entity_flat(entity, healing, overheal)
    return
}

/*
William Duprey
4/9/26
Heals an entity by a flat value.
- entity: Entity struct to modify (Entity pointer)
- healing: amount to heal (int)
- overheal: whether to cap healing at max health
            Defaults to false
Returns the damage dealt to armour and health as separate integers.
TODO: Decide whether overhealing should also be returned? (probably)
*/
//@(export)
heal_entity_flat :: proc "c" (entity: ^Entity, healing: int, overheal: bool = false) -> (healthRestored: int){
    context = runtime.default_context()
    // Make sure we don't blow up from a nil pointer
    // or weird math happening with negative healing
    assert(entity != nil, "Invalid argument to damage_entity: entity pointer cannot be nil")
    assert(healing >= 0, "Invalid argument to damage_entity: healing cannot be negative")

    // Retrieve health values from the entity struct
    // to avoid repeatedly accessing the field
    health: int = entity.health.current

    // Use a helper procedure so I don't repeat myself
    // - This procedure does alter entity.health.current,
    //   so there is no need to set it at the end of this
    //   procedure.
    heal_pair(&(entity.health), healing, overheal)

    // Compare the starting health to get the actual healing done
    healthRestored = entity.health.current - health

    return // healthRestored
}

/*
William Duprey
4/16/26
Removes a number of stacks of the given status from the entity.
- entity: pointer to the entity
- status: the type of status to remove
- count: number of status stacks to remove
*/
//@(export)
remove_status_count :: proc "c" (entity: ^Entity, status: Statuses, count: int){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to remove_status_count: entity pointer cannot be nil")
    assert(count > 0, "Invalid argument to remove_status_count: status count must be at least 1")

    // Reduce status count to a max of 0
    entity.status[status] = max(0, entity.status[status] - count)
}

/*
William Duprey
4/16/26
Removes all stacks of the given status.
- entity: pointer to the entity
- status: the type of status to clear
*/
//@(export)
remove_status_all :: proc "c" (entity: ^Entity, status: Statuses){
    context = runtime.default_context()
    assert(entity != nil, "Invalid argument to remove_status_all: entity pointer cannot be nil")
    
    // Remove all stacks of status
    entity.status[status] = 0
}

@(export, link_name="get_pair")
get_pair :: proc "c" () -> (Pair(i32)){
    pair := Pair(i32){3, 5}
    return pair
}